services:
  - type: web
    name: signavatar
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
